### ISSUE TITLE
A package  alternative to DIY-ABC is expected.

### ISSUE THREAD

**Issue by xiekunwhy** [mnavascues/ABCRFtutorial#1]
Hi,
A package  alternative to DIY-ABC(http://www1.montpellier.inra.fr/CBGP/diyabc/) is expected as it is very old and slow and often reporting errors.

Cheers.
Kun.

**Comment by mnavascues** [comment]
The materials distributed in this repository are intended for teaching/learning support, not as a substitute/alternative to any software for ABC analysis.
